### ISSUE TITLE
Perplex does not create temporary files directory 

### ISSUE THREAD

**Issue by lorenaacuna** [astro-seanwhy/ExoInt#9]
Hi Haiyang,

I'm trying to run the default test of the Perplex module. I run in the terminal:

`python3 mineral_quick_solver.py MRfiles/MR_example.csv`

from the pyExoInt/Mineral directory, and I get the following error: 

```
mkdir: cannot create directory ‘/data/beegfs/astro-storage/groups/kreidberg/acuna/acuna_category_A_data/ExoInt-master/pyExoInt/Mineral/Utilities/tmp_files/42301’: No such file or directory
Traceback (most recent call last):
  File "/data/beegfs/astro-storage/groups/kreidberg/acuna/acuna_category_A_data/ExoInt-master/pyExoInt/Mineral/mineral_quick_solver.py", line 86, in <module>
    P.solve_structure() 
  File "/data/beegfs/astro-storage/groups/kreidberg/acuna/acuna_category_A_data/ExoInt-master/pyExoInt/Mineral/Utilities/interior_model.py", line 814, in solve_structure
    mantle_dict, Phases = call_mineralogy_calculation(
  File "/data/beegfs/astro-storage/groups/kreidberg/acuna/acuna_category_A_data/ExoInt-master/pyExoInt/Mineral/Utilities/interior_model.py", line 279, in call_mineralogy_calculation
    mantlegrid = open(path + "/tmp_files/" + subpath_name + "/mantlegrid.dat", "w")
FileNotFoundError: [Errno 2] No such file or directory: '/data/beegfs/astro-storage/groups/kreidberg/acuna/acuna_category_A_data/ExoInt-master/pyExoInt/Mineral/Utilities/tmp_files/42301/mantlegrid.dat'

```

I'm using a node in a computing cluster with the following specs: Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz. The OS is Rocky Linux 9.4 (Blue Onyx).

I did a quick word search in the Python files for "mkdir", but I didn't find any, so I suspect this error may come from the Perplex binaries. Do you think there is a way to test this further or a solution?

Thanks a lot in advance.

**Comment by astro-seanwhy** [comment]
Hi Lorena, 

Thank you for the report! 

The error can be eliminated by manually creating an empty folder, 'tmp_files', under the directory of 'Utilities', with mkdir. 

But afterwards, you might encounter an EOF error, which is related to the character limit of the path length of Perple_X, as noted in the README file for the 'Mineral' module. To solve it, please re-place the whole 'Mineral' folder into your home directory, i.e., "../acuna". In principal, you shall also place 'pyExoInt' directly under your home directory, too. Upon the replacements, you shall modify the datapath in the 'mineral_quick_solver.py' file (or its equivalents), namely line 34 to be like:
datapath = '../pyExoInt/output' (i.e., directing to the stoichiometric compositional output from pyExoInt). 

This is a temporary solution, but I hope it may help successfully run the Mineral module. 

Let me know in case of any further issues. Maybe I should open a Slack channel for the convenience of communication for the users/co-developers of ExoInt :)

Best wishes.
